/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pratica04Luzo;

public class Library {
    String interruptor = "";
    
    public void ligarInterruptor() {
    	interruptor = "on";
    }
    
    public void desligarInterruptor() {
    	interruptor = "off";
    }
	
    
    public boolean someLibraryMethod() {
        //ligarInterruptor();
        desligarInterruptor();
    	if (interruptor == "on")
        	return true;
        else
        	return false;
		
    }
}
